server:
  port: 7000
  
api-address:
    client:
        address:
            url: http://localhost:8002/addresses

spring:
    data:
        mongodb:
            uri: mongodb://localhost:27017/hexagonal